name: Deploy to Production
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Set Railway deploy image
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
         railway service source connect \
           --project 4fd9a5e1-d80f-425a-9ce1-09d9ca994bb0 \
           --image reviendra/booking-service:${{ inputs.image_tag }} \
           --service c42825b7-08da-4323-8206-47a4438d80fd \
           --environment Production

      - name: Deploy to production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway redeploy \
            --project 4fd9a5e1-d80f-425a-9ce1-09d9ca994bb0 \
            --environment Staging \
            --service c42825b7-08da-4323-8206-47a4438d80fd \
            --yes